### ISSUE TITLE
Blanket does not work with async traits

### ISSUE THREAD

**Issue by nwalfield** [althonos/blanket#11]
[Rust 1.75 introduced async methods](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html), but they cannot be used with blanket 0.2.  Consider:

```
use blanket;

#[blanket::blanket(derive(Ref))]
trait Foo {
    async fn bar(&self);
}

fn main() {
    println!("Hello, world!");
}
```

```
$ cargo build
   Compiling blanket v0.1.0 (/tmp/blanket)
error[E0308]: mismatched types
 --> src/main.rs:3:1
  |
3 | #[blanket::blanket(derive(Ref))]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found associated type
  |
  = note:    expected unit type `()`
          found associated type `impl Future<Output = ()>`
note: calling an async function returns a future
 --> src/main.rs:3:1
  |
3 | #[blanket::blanket(derive(Ref))]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: this error originates in the attribute macro `blanket::blanket` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider `await`ing on the `Future`
  |
3 | #[blanket::blanket(derive(Ref))].await
  |                                 ++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `blanket` (bin "blanket") due to 1 previous error
```

The following compiles fine (just remove the `async` from `Foo::bar`):

```
use blanket;

#[blanket::blanket(derive(Ref))]
trait Foo {
    fn bar(&self);
}

fn main() {
    println!("Hello, world!");
}
```

Changing `bar` to be an `async` method () fails:

**Comment by althonos** [comment]
I have pushed a fix to the `master` branch, please try using it and if it works as expected I will be making a new release.

**Comment by nwalfield** [comment]
Thanks for working on this!

I've tried using the code from git, and can confirm that [it still works with the project that uses 0.3](https://gitlab.com/sequoia-pgp/sequoia-keystore/-/blob/05e35c2c/backend/Cargo.toml?ref_type=heads#L20).  I also tried it with a toy example that uses a trait with async methods.  It didn't blow up in the sense that it compiled, but I didn't intensely check that the functionality works.

**Comment by althonos** [comment]
That's fine by me! In general I'll go with a "don't fix what's not broken" approach for this package, if it doesn't blow up on reasonable trait impls I'll be happy with it.

**Comment by althonos** [comment]
I pushed `v0.4.0` to crates.io, feel free to open another issue if there is something not working :+1:

**Comment by nwalfield** [comment]
Thanks!
