### ISSUE TITLE
Failed on trait with generic arguments.

### ISSUE THREAD

**Issue by najamelan** [althonos/blanket#2]
I wanted to give blanket a try because, well, boilerplate. But:

```rust
#[ blanket(derive( Ref, Mut, Box, Rc )) ]
//
pub trait SpawnHandle<Out: 'static + Send>
{
   ...
}
```

gave me:

```
error[E0658]: associated type bounds are unstable
  --> src/iface/spawn_handle.rs:57:23
   |
57 | pub trait SpawnHandle<Out: 'static + Send>
   |                       ^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information
```

and 

```
error[E0107]: missing generics for trait `spawn_handle::SpawnHandle`
  --> src/iface/spawn_handle.rs:57:11
   |
57 | pub trait SpawnHandle<Out: 'static + Send>
   |           ^^^^^^^^^^^ expected 1 type argument
   |
note: trait defined here, with 1 type parameter: `Out`
  --> src/iface/spawn_handle.rs:57:11
   |
57 | pub trait SpawnHandle<Out: 'static + Send>
   |           ^^^^^^^^^^^ ---
help: use angle brackets to add missing type argument
   |
57 | pub trait SpawnHandle<Out><Out: 'static + Send>
```

It generates:

```rust 
impl<Out: 'static + Send, SH: SpawnHandle<Out: 'static + Send>>
            SpawnHandle<Out: 'static + Send> for Box<SH>
```

Where the manual implementation would do:

```rust
impl<T, Out> SpawnHandle<Out> for Box<T> 

   where T  : SpawnHandle<Out> + ?Sized, 
         Out: 'static + Send
```

So it seems the issue is that the trait bounds on the generic type are repeated and they shouldn't.

**Comment by althonos** [comment]
Hi @najamelan 

thanks for your interest and for the report! I have normally fixed this, and while I am not confident 100% of the weird cases with multiple trait generics are supported, at least your example compiles with the latest release I made (`v0.1.5`). Feel free to reopen if the issue persists!

**Comment by najamelan** [comment]
Thanks a lot for the quick resolution! Are you open to pull requests? I would have a stab at supporting `Arc`. Also I noticed it doesn't seem to work with associated types. I might try to fix that too. Is there a specific challenge why `Arc` is not implemented? Like is it fundamentally different from `Rc`?

**Comment by althonos** [comment]
Sure ! You should be able to get `Arc` working by just copying the `Rc` implementation indeed. PRs are very welcome :)
